@echo off
rem Builds the FastHash tests and benchmark for Win32 and Win64.
rem Output: Win32\Release and Win64\Release next to this script.
rem The asm in Asm\*.inc is generated by Tools\gen_*.pl (perl); it is checked
rem in, so building does not need perl.
setlocal
call "C:\Program Files (x86)\Embarcadero\Studio\37.0\bin\rsvars.bat" >nul
cd /d "%~dp0"

if not exist Win32\Release mkdir Win32\Release
if not exist Win64\Release mkdir Win64\Release

echo === Win32: tests
pushd Tests
dcc32 -B -Q -E"..\Win32\Release" -NU"..\Win32\Release" FastHashTests.dpr
if errorlevel 1 goto :err
echo === Win64: tests
dcc64 -B -Q -E"..\Win64\Release" -NU"..\Win64\Release" FastHashTests.dpr
if errorlevel 1 goto :err
popd

echo === Win32: benchmark
pushd Bench
dcc32 -B -Q -E"..\Win32\Release" -NU"..\Win32\Release" FastHashBench.dpr
if errorlevel 1 goto :err
echo === Win64: benchmark
dcc64 -B -Q -E"..\Win64\Release" -NU"..\Win64\Release" FastHashBench.dpr
if errorlevel 1 goto :err
popd

echo.
echo BUILD OK
goto :eof

:err
popd
echo.
echo BUILD FAILED
exit /b 1
