unit FastHash.MD5;

{
  MD5 block compression: a Pascal reference and an unrolled scalar asm core
  (Asm\MD5.x86.inc / Asm\MD5.x64.inc, generated by Tools\gen_md5.pl).

  MD5's 64 steps form one long dependency chain, so SIMD cannot speed up a
  single stream; the asm gains come from register allocation and the
  shorter-critical-path forms of F/G/H/I.
}

interface

{$I FastHash.inc}

uses
  FastHash.CPU;

type
  TMD5CompressProc = TFastHashBlockProc;

var
  /// <summary>Compresses Blocks 64-byte blocks into State (4 Cardinals).</summary>
  MD5Compress: TMD5CompressProc;

procedure MD5CompressPascal(State: Pointer; Data: PByte; Blocks: NativeUInt);
/// <summary>Binds MD5Compress to the best implementation at or below MaxLevel; returns the level used.</summary>
function MD5SetMaxLevel(MaxLevel: TFastHashLevel): TFastHashLevel;
function MD5ActiveLevel: TFastHashLevel;
/// <summary>Name of the implementation in use, e.g. 'A64 asm'.</summary>
function MD5ActiveImplementation: string;
/// <summary>Every implementation this CPU can run, Pascal first, in order of preference within each level.</summary>
function MD5Implementations: TArray<TFastHashBlockImpl>;

implementation

{$Q-}{$R-}

var
  Active: TFastHashBlockImpl;

{$POINTERMATH ON}
procedure MD5CompressPascal(State: Pointer; Data: PByte; Blocks: NativeUInt);
var
  S: PCardinal;
  X: PCardinal;
  a, b, c, d: Cardinal;

  function RL(x: Cardinal; n: Byte): Cardinal; inline;
  begin
    Result := (x shl n) or (x shr (32 - n));
  end;

begin
  S := State;
  while Blocks > 0 do
  begin
    X := PCardinal(Data);   // MD5 words are little-endian, like x86
    a := S[0]; b := S[1]; c := S[2]; d := S[3];

    a := b + RL(a + (d xor (b and (c xor d))) + X[ 0] + $d76aa478,  7);
    d := a + RL(d + (c xor (a and (b xor c))) + X[ 1] + $e8c7b756, 12);
    c := d + RL(c + (b xor (d and (a xor b))) + X[ 2] + $242070db, 17);
    b := c + RL(b + (a xor (c and (d xor a))) + X[ 3] + $c1bdceee, 22);
    a := b + RL(a + (d xor (b and (c xor d))) + X[ 4] + $f57c0faf,  7);
    d := a + RL(d + (c xor (a and (b xor c))) + X[ 5] + $4787c62a, 12);
    c := d + RL(c + (b xor (d and (a xor b))) + X[ 6] + $a8304613, 17);
    b := c + RL(b + (a xor (c and (d xor a))) + X[ 7] + $fd469501, 22);
    a := b + RL(a + (d xor (b and (c xor d))) + X[ 8] + $698098d8,  7);
    d := a + RL(d + (c xor (a and (b xor c))) + X[ 9] + $8b44f7af, 12);
    c := d + RL(c + (b xor (d and (a xor b))) + X[10] + $ffff5bb1, 17);
    b := c + RL(b + (a xor (c and (d xor a))) + X[11] + $895cd7be, 22);
    a := b + RL(a + (d xor (b and (c xor d))) + X[12] + $6b901122,  7);
    d := a + RL(d + (c xor (a and (b xor c))) + X[13] + $fd987193, 12);
    c := d + RL(c + (b xor (d and (a xor b))) + X[14] + $a679438e, 17);
    b := c + RL(b + (a xor (c and (d xor a))) + X[15] + $49b40821, 22);

    a := b + RL(a + (c xor (d and (b xor c))) + X[ 1] + $f61e2562,  5);
    d := a + RL(d + (b xor (c and (a xor b))) + X[ 6] + $c040b340,  9);
    c := d + RL(c + (a xor (b and (d xor a))) + X[11] + $265e5a51, 14);
    b := c + RL(b + (d xor (a and (c xor d))) + X[ 0] + $e9b6c7aa, 20);
    a := b + RL(a + (c xor (d and (b xor c))) + X[ 5] + $d62f105d,  5);
    d := a + RL(d + (b xor (c and (a xor b))) + X[10] + $02441453,  9);
    c := d + RL(c + (a xor (b and (d xor a))) + X[15] + $d8a1e681, 14);
    b := c + RL(b + (d xor (a and (c xor d))) + X[ 4] + $e7d3fbc8, 20);
    a := b + RL(a + (c xor (d and (b xor c))) + X[ 9] + $21e1cde6,  5);
    d := a + RL(d + (b xor (c and (a xor b))) + X[14] + $c33707d6,  9);
    c := d + RL(c + (a xor (b and (d xor a))) + X[ 3] + $f4d50d87, 14);
    b := c + RL(b + (d xor (a and (c xor d))) + X[ 8] + $455a14ed, 20);
    a := b + RL(a + (c xor (d and (b xor c))) + X[13] + $a9e3e905,  5);
    d := a + RL(d + (b xor (c and (a xor b))) + X[ 2] + $fcefa3f8,  9);
    c := d + RL(c + (a xor (b and (d xor a))) + X[ 7] + $676f02d9, 14);
    b := c + RL(b + (d xor (a and (c xor d))) + X[12] + $8d2a4c8a, 20);

    a := b + RL(a + (b xor c xor d) + X[ 5] + $fffa3942,  4);
    d := a + RL(d + (a xor b xor c) + X[ 8] + $8771f681, 11);
    c := d + RL(c + (d xor a xor b) + X[11] + $6d9d6122, 16);
    b := c + RL(b + (c xor d xor a) + X[14] + $fde5380c, 23);
    a := b + RL(a + (b xor c xor d) + X[ 1] + $a4beea44,  4);
    d := a + RL(d + (a xor b xor c) + X[ 4] + $4bdecfa9, 11);
    c := d + RL(c + (d xor a xor b) + X[ 7] + $f6bb4b60, 16);
    b := c + RL(b + (c xor d xor a) + X[10] + $bebfbc70, 23);
    a := b + RL(a + (b xor c xor d) + X[13] + $289b7ec6,  4);
    d := a + RL(d + (a xor b xor c) + X[ 0] + $eaa127fa, 11);
    c := d + RL(c + (d xor a xor b) + X[ 3] + $d4ef3085, 16);
    b := c + RL(b + (c xor d xor a) + X[ 6] + $04881d05, 23);
    a := b + RL(a + (b xor c xor d) + X[ 9] + $d9d4d039,  4);
    d := a + RL(d + (a xor b xor c) + X[12] + $e6db99e5, 11);
    c := d + RL(c + (d xor a xor b) + X[15] + $1fa27cf8, 16);
    b := c + RL(b + (c xor d xor a) + X[ 2] + $c4ac5665, 23);

    a := b + RL(a + (c xor (b or not d)) + X[ 0] + $f4292244,  6);
    d := a + RL(d + (b xor (a or not c)) + X[ 7] + $432aff97, 10);
    c := d + RL(c + (a xor (d or not b)) + X[14] + $ab9423a7, 15);
    b := c + RL(b + (d xor (c or not a)) + X[ 5] + $fc93a039, 21);
    a := b + RL(a + (c xor (b or not d)) + X[12] + $655b59c3,  6);
    d := a + RL(d + (b xor (a or not c)) + X[ 3] + $8f0ccc92, 10);
    c := d + RL(c + (a xor (d or not b)) + X[10] + $ffeff47d, 15);
    b := c + RL(b + (d xor (c or not a)) + X[ 1] + $85845dd1, 21);
    a := b + RL(a + (c xor (b or not d)) + X[ 8] + $6fa87e4f,  6);
    d := a + RL(d + (b xor (a or not c)) + X[15] + $fe2ce6e0, 10);
    c := d + RL(c + (a xor (d or not b)) + X[ 6] + $a3014314, 15);
    b := c + RL(b + (d xor (c or not a)) + X[13] + $4e0811a1, 21);
    a := b + RL(a + (c xor (b or not d)) + X[ 4] + $f7537e82,  6);
    d := a + RL(d + (b xor (a or not c)) + X[11] + $bd3af235, 10);
    c := d + RL(c + (a xor (d or not b)) + X[ 2] + $2ad7d2bb, 15);
    b := c + RL(b + (d xor (c or not a)) + X[ 9] + $eb86d391, 21);

    Inc(S[0], a); Inc(S[1], b); Inc(S[2], c); Inc(S[3], d);
    Inc(Data, 64);
    Dec(Blocks);
  end;
end;
{$POINTERMATH OFF}

{$IFDEF FASTHASH_X86ASM}
  {$IF defined(CPUX64)}
    {$I Asm\MD5.x64.inc}
  {$ELSE}
    {$I Asm\MD5.x86.inc}
  {$ENDIF}
{$ENDIF}

{$IFDEF FASTHASH_ARM64}
procedure fh_md5_asm(State: Pointer; Data: PByte; Blocks: NativeUInt); external FastHashArmObj name 'fh_md5_asm';
procedure fh_md5_c(State: Pointer; Data: PByte; Blocks: NativeUInt); external FastHashArmObj name 'fh_md5_c';
{$ENDIF}

function MD5Implementations: TArray<TFastHashBlockImpl>;
begin
  // in order of preference within each level (see the README's benchmark notes)
  Result := [FastHashImpl('Pascal', fhlPascal, MD5CompressPascal)];
{$IFDEF FASTHASH_X86ASM}
  if fhlScalar in FastHashSupportedLevels then
    Result := Result + [FastHashImpl('x86 asm', fhlScalar, MD5CompressScalar)];
{$ENDIF}
{$IFDEF FASTHASH_ARM64}
  Result := Result + [FastHashImpl('A64 asm', fhlScalar, fh_md5_asm), FastHashImpl('C', fhlScalar, fh_md5_c)];
{$ENDIF}
end;

function MD5SetMaxLevel(MaxLevel: TFastHashLevel): TFastHashLevel;
begin
  Active := FastHashSelect(MD5Implementations, MaxLevel);
  MD5Compress := Active.Proc;
  Result := Active.Level;
end;

function MD5ActiveLevel: TFastHashLevel;
begin
  Result := Active.Level;
end;

function MD5ActiveImplementation: string;
begin
  Result := Active.Name;
end;

initialization
  MD5SetMaxLevel(High(TFastHashLevel));

end.
