unit FastHash.SHA256;

{
  SHA-224/SHA-256 block compression: Pascal reference plus three asm cores
  (Asm\SHA256.x86.inc / Asm\SHA256.x64.inc, generated by Tools\gen_sha256.pl):

    Scalar  unrolled integer rounds with a 16-word circular schedule
    AVX2    two blocks' W+K schedule computed together in ymm registers,
            then BMI1/BMI2 (andn/rorx) rounds
    SHANI   Intel SHA extensions
}

interface

{$I FastHash.inc}

uses
  FastHash.CPU;

type
  TSHA256CompressProc = TFastHashBlockProc;

var
  /// <summary>Compresses Blocks 64-byte blocks into State (8 Cardinals).</summary>
  SHA256Compress: TSHA256CompressProc;

procedure SHA256CompressPascal(State: Pointer; Data: PByte; Blocks: NativeUInt);
function SHA256SetMaxLevel(MaxLevel: TFastHashLevel): TFastHashLevel;
function SHA256ActiveLevel: TFastHashLevel;
/// <summary>Name of the implementation in use, e.g. 'A64 asm'.</summary>
function SHA256ActiveImplementation: string;
/// <summary>Every implementation this CPU can run, Pascal first, in order of preference within each level.</summary>
function SHA256Implementations: TArray<TFastHashBlockImpl>;

implementation

{$Q-}{$R-}

const
  K256: array[0..63] of Cardinal = (
    $428a2f98, $71374491, $b5c0fbcf, $e9b5dba5, $3956c25b, $59f111f1, $923f82a4, $ab1c5ed5,
    $d807aa98, $12835b01, $243185be, $550c7dc3, $72be5d74, $80deb1fe, $9bdc06a7, $c19bf174,
    $e49b69c1, $efbe4786, $0fc19dc6, $240ca1cc, $2de92c6f, $4a7484aa, $5cb0a9dc, $76f988da,
    $983e5152, $a831c66d, $b00327c8, $bf597fc7, $c6e00bf3, $d5a79147, $06ca6351, $14292967,
    $27b70a85, $2e1b2138, $4d2c6dfc, $53380d13, $650a7354, $766a0abb, $81c2c92e, $92722c85,
    $a2bfe8a1, $a81a664b, $c24b8b70, $c76c51a3, $d192e819, $d6990624, $f40e3585, $106aa070,
    $19a4c116, $1e376c08, $2748774c, $34b0bcb5, $391c0cb3, $4ed8aa4a, $5b9cca4f, $682e6ff3,
    $748f82ee, $78a5636f, $84c87814, $8cc70208, $90befffa, $a4506ceb, $bef9a3f7, $c67178f2);

var
  Active: TFastHashBlockImpl;
  // 64-byte aligned constants for the SHA-NI code (legacy-SSE memory operands
  // must be 16-byte aligned). The AVX2 code uses the named rows in the .inc.
  SHA256Consts: PByte;

type
  TSHA256ConstPool = packed record
    NIBswap: array[0..15] of Byte;
    K: array[0..63] of Cardinal;
  end;

procedure InitConsts;
var
  P: TSHA256ConstPool;
  I: Integer;
begin
  for I := 0 to 15 do
    P.NIBswap[I] := (I and not 3) + 3 - (I and 3);
  Move(K256, P.K, SizeOf(K256));
  SHA256Consts := FastHashAlignedConst(P, SizeOf(P));
end;

{$POINTERMATH ON}
procedure SHA256CompressPascal(State: Pointer; Data: PByte; Blocks: NativeUInt);
var
  S: PCardinal;
  W: array[0..63] of Cardinal;
  a, b, c, d, e, f, g, h, s0, s1, t1, t2: Cardinal;
  I: Integer;

  function ROR(x: Cardinal; n: Byte): Cardinal; inline;
  begin
    Result := (x shr n) or (x shl (32 - n));
  end;

begin
  S := State;
  while Blocks > 0 do
  begin
    for I := 0 to 15 do
      W[I] := (Cardinal(Data[4 * I]) shl 24) or (Cardinal(Data[4 * I + 1]) shl 16) or
              (Cardinal(Data[4 * I + 2]) shl 8) or Cardinal(Data[4 * I + 3]);
    for I := 16 to 63 do
    begin
      s0 := ROR(W[I - 15], 7) xor ROR(W[I - 15], 18) xor (W[I - 15] shr 3);
      s1 := ROR(W[I - 2], 17) xor ROR(W[I - 2], 19) xor (W[I - 2] shr 10);
      W[I] := W[I - 16] + s0 + W[I - 7] + s1;
    end;
    a := S[0]; b := S[1]; c := S[2]; d := S[3];
    e := S[4]; f := S[5]; g := S[6]; h := S[7];
    for I := 0 to 63 do
    begin
      t1 := h + (ROR(e, 6) xor ROR(e, 11) xor ROR(e, 25)) + (g xor (e and (f xor g))) + K256[I] + W[I];
      t2 := (ROR(a, 2) xor ROR(a, 13) xor ROR(a, 22)) + ((a and b) or (c and (a or b)));
      h := g; g := f; f := e; e := d + t1;
      d := c; c := b; b := a; a := t1 + t2;
    end;
    Inc(S[0], a); Inc(S[1], b); Inc(S[2], c); Inc(S[3], d);
    Inc(S[4], e); Inc(S[5], f); Inc(S[6], g); Inc(S[7], h);
    Inc(Data, 64);
    Dec(Blocks);
  end;
end;
{$POINTERMATH OFF}

{$IFDEF FASTHASH_X86ASM}
  {$IF defined(CPUX64)}
    {$I Asm\SHA256.x64.inc}
  {$ELSE}
    {$I Asm\SHA256.x86.inc}
  {$ENDIF}
{$ENDIF}

{$IFDEF FASTHASH_ARM64}
procedure fh_sha256_asm(State: Pointer; Data: PByte; Blocks: NativeUInt); external FastHashArmObj name 'fh_sha256_asm';
procedure fh_sha256_c(State: Pointer; Data: PByte; Blocks: NativeUInt); external FastHashArmObj name 'fh_sha256_c';
procedure fh_sha256_ce_asm(State: Pointer; Data: PByte; Blocks: NativeUInt); external FastHashArmObj name 'fh_sha256_ce_asm';
procedure fh_sha256_ce_c(State: Pointer; Data: PByte; Blocks: NativeUInt); external FastHashArmObj name 'fh_sha256_ce_c';
{$ENDIF}

function SHA256Implementations: TArray<TFastHashBlockImpl>;
{$IFDEF FASTHASH_X86ASM}
var
  Supported: TFastHashLevels;
{$ENDIF}
begin
  // in order of preference within each level (see the README's benchmark notes)
  Result := [FastHashImpl('Pascal', fhlPascal, SHA256CompressPascal)];
{$IFDEF FASTHASH_X86ASM}
  Supported := FastHashSupportedLevels;
  if fhlScalar in Supported then
    Result := Result + [FastHashImpl('x86 asm', fhlScalar, SHA256CompressScalar)];
  if fhlSIMD in Supported then
    Result := Result + [FastHashImpl('AVX2 asm', fhlSIMD, SHA256CompressAVX2)];
  if fhlCrypto in Supported then
    Result := Result + [FastHashImpl('SHA-NI asm', fhlCrypto, SHA256CompressSHANI)];
{$ENDIF}
{$IFDEF FASTHASH_ARM64}
  Result := Result + [FastHashImpl('A64 asm', fhlScalar, fh_sha256_asm), FastHashImpl('C', fhlScalar, fh_sha256_c)];
  if CPUHasSHA then
    Result := Result + [FastHashImpl('CE asm', fhlCrypto, fh_sha256_ce_asm), FastHashImpl('CE C', fhlCrypto, fh_sha256_ce_c)];
{$ENDIF}
end;

function SHA256SetMaxLevel(MaxLevel: TFastHashLevel): TFastHashLevel;
begin
  Active := FastHashSelect(SHA256Implementations, MaxLevel);
  SHA256Compress := Active.Proc;
  Result := Active.Level;
end;

function SHA256ActiveLevel: TFastHashLevel;
begin
  Result := Active.Level;
end;

function SHA256ActiveImplementation: string;
begin
  Result := Active.Name;
end;

initialization
  InitConsts;
  SHA256SetMaxLevel(High(TFastHashLevel));

end.
