unit FastHash.SHA1;

{
  SHA-1 block compression: Pascal reference plus three asm cores
  (Asm\SHA1.x86.inc / Asm\SHA1.x64.inc, generated by Tools\gen_sha1.pl):

    Scalar  unrolled integer rounds with a 16-word circular schedule
    AVX2    two blocks' W+K schedule computed together in ymm registers,
            then BMI1/BMI2 (andn/rorx) rounds
    SHANI   Intel SHA extensions
}

interface

{$I FastHash.inc}

uses
  FastHash.CPU;

type
  TSHA1CompressProc = TFastHashBlockProc;

var
  /// <summary>Compresses Blocks 64-byte blocks into State (5 Cardinals).</summary>
  SHA1Compress: TSHA1CompressProc;

procedure SHA1CompressPascal(State: Pointer; Data: PByte; Blocks: NativeUInt);
function SHA1SetMaxLevel(MaxLevel: TFastHashLevel): TFastHashLevel;
function SHA1ActiveLevel: TFastHashLevel;
/// <summary>Name of the implementation in use, e.g. 'A64 asm'.</summary>
function SHA1ActiveImplementation: string;
/// <summary>Every implementation this CPU can run, Pascal first, in order of preference within each level.</summary>
function SHA1Implementations: TArray<TFastHashBlockImpl>;

implementation

{$Q-}{$R-}

var
  Active: TFastHashBlockImpl;
  // 64-byte aligned constants for the SHA-NI code (legacy-SSE memory operands
  // must be 16-byte aligned). The AVX2 code uses the named rows in the .inc.
  SHA1Consts: PByte;

type
  TSHA1ConstPool = packed record
    NIFlip: array[0..15] of Byte;
    NIUpper: array[0..3] of Cardinal;
  end;

procedure InitConsts;
var
  P: TSHA1ConstPool;
  I: Integer;
begin
  for I := 0 to 15 do
    P.NIFlip[I] := 15 - I;
  P.NIUpper[0] := 0;
  P.NIUpper[1] := 0;
  P.NIUpper[2] := 0;
  P.NIUpper[3] := $FFFFFFFF;
  SHA1Consts := FastHashAlignedConst(P, SizeOf(P));
end;

{$POINTERMATH ON}
procedure SHA1CompressPascal(State: Pointer; Data: PByte; Blocks: NativeUInt);
var
  S: PCardinal;
  W: array[0..79] of Cardinal;
  A, B, C, D, E, T: Cardinal;
  I: Integer;
begin
  S := State;
  while Blocks > 0 do
  begin
    for I := 0 to 15 do
      W[I] := (Cardinal(Data[4 * I]) shl 24) or (Cardinal(Data[4 * I + 1]) shl 16) or
              (Cardinal(Data[4 * I + 2]) shl 8) or Cardinal(Data[4 * I + 3]);
    for I := 16 to 79 do
    begin
      T := W[I - 3] xor W[I - 8] xor W[I - 14] xor W[I - 16];
      W[I] := (T shl 1) or (T shr 31);
    end;
    A := S[0]; B := S[1]; C := S[2]; D := S[3]; E := S[4];
    for I := 0 to 79 do
    begin
      case I of
        0..19:  T := (D xor (B and (C xor D))) + $5A827999;
        20..39: T := (B xor C xor D) + $6ED9EBA1;
        40..59: T := ((B and C) or (D and (B or C))) + $8F1BBCDC;
      else
        T := (B xor C xor D) + $CA62C1D6;
      end;
      T := T + ((A shl 5) or (A shr 27)) + E + W[I];
      E := D; D := C; C := (B shl 30) or (B shr 2); B := A; A := T;
    end;
    Inc(S[0], A); Inc(S[1], B); Inc(S[2], C); Inc(S[3], D); Inc(S[4], E);
    Inc(Data, 64);
    Dec(Blocks);
  end;
end;
{$POINTERMATH OFF}

{$IFDEF FASTHASH_X86ASM}
  {$IF defined(CPUX64)}
    {$I Asm\SHA1.x64.inc}
  {$ELSE}
    {$I Asm\SHA1.x86.inc}
  {$ENDIF}
{$ENDIF}

{$IFDEF FASTHASH_ARM64}
procedure fh_sha1_asm(State: Pointer; Data: PByte; Blocks: NativeUInt); external FastHashArmObj name 'fh_sha1_asm';
procedure fh_sha1_c(State: Pointer; Data: PByte; Blocks: NativeUInt); external FastHashArmObj name 'fh_sha1_c';
procedure fh_sha1_ce_asm(State: Pointer; Data: PByte; Blocks: NativeUInt); external FastHashArmObj name 'fh_sha1_ce_asm';
procedure fh_sha1_ce_c(State: Pointer; Data: PByte; Blocks: NativeUInt); external FastHashArmObj name 'fh_sha1_ce_c';
{$ENDIF}

function SHA1Implementations: TArray<TFastHashBlockImpl>;
{$IFDEF FASTHASH_X86ASM}
var
  Supported: TFastHashLevels;
{$ENDIF}
begin
  // in order of preference within each level (see the README's benchmark notes)
  Result := [FastHashImpl('Pascal', fhlPascal, SHA1CompressPascal)];
{$IFDEF FASTHASH_X86ASM}
  Supported := FastHashSupportedLevels;
  if fhlScalar in Supported then
    Result := Result + [FastHashImpl('x86 asm', fhlScalar, SHA1CompressScalar)];
  if fhlSIMD in Supported then
    Result := Result + [FastHashImpl('AVX2 asm', fhlSIMD, SHA1CompressAVX2)];
  if fhlCrypto in Supported then
    Result := Result + [FastHashImpl('SHA-NI asm', fhlCrypto, SHA1CompressSHANI)];
{$ENDIF}
{$IFDEF FASTHASH_ARM64}
  Result := Result + [FastHashImpl('A64 asm', fhlScalar, fh_sha1_asm), FastHashImpl('C', fhlScalar, fh_sha1_c)];
  if CPUHasSHA then
    Result := Result + [FastHashImpl('CE asm', fhlCrypto, fh_sha1_ce_asm), FastHashImpl('CE C', fhlCrypto, fh_sha1_ce_c)];
{$ENDIF}
end;

function SHA1SetMaxLevel(MaxLevel: TFastHashLevel): TFastHashLevel;
begin
  Active := FastHashSelect(SHA1Implementations, MaxLevel);
  SHA1Compress := Active.Proc;
  Result := Active.Level;
end;

function SHA1ActiveLevel: TFastHashLevel;
begin
  Result := Active.Level;
end;

function SHA1ActiveImplementation: string;
begin
  Result := Active.Name;
end;

initialization
  InitConsts;
  SHA1SetMaxLevel(High(TFastHashLevel));

end.
