unit FastHash.SHA1;

{
  SHA-1 block compression: Pascal reference plus three asm cores
  (Asm\SHA1.x86.inc / Asm\SHA1.x64.inc, generated by Tools\gen_sha1.pl):

    Scalar  unrolled integer rounds with a 16-word circular schedule
    AVX2    two blocks' W+K schedule computed together in ymm registers,
            then BMI1/BMI2 (andn/rorx) rounds
    SHANI   Intel SHA extensions
}

interface

uses
  FastHash.CPU;

type
  TSHA1CompressProc = procedure(State: Pointer; Data: PByte; Blocks: NativeUInt);

var
  /// <summary>Compresses Blocks 64-byte blocks into State (5 Cardinals).</summary>
  SHA1Compress: TSHA1CompressProc;

procedure SHA1CompressPascal(State: Pointer; Data: PByte; Blocks: NativeUInt);
function SHA1SetMaxLevel(MaxLevel: TFastHashLevel): TFastHashLevel;
function SHA1ActiveLevel: TFastHashLevel;

implementation

{$Q-}{$R-}

var
  ActiveLevel: TFastHashLevel;
  // 64-byte aligned constants for the SHA-NI code (legacy-SSE memory operands
  // must be 16-byte aligned). The AVX2 code uses the named rows in the .inc.
  SHA1Consts: PByte;

type
  TSHA1ConstPool = packed record
    NIFlip: array[0..15] of Byte;
    NIUpper: array[0..3] of Cardinal;
  end;

procedure InitConsts;
var
  P: TSHA1ConstPool;
  I: Integer;
begin
  for I := 0 to 15 do
    P.NIFlip[I] := 15 - I;
  P.NIUpper[0] := 0;
  P.NIUpper[1] := 0;
  P.NIUpper[2] := 0;
  P.NIUpper[3] := $FFFFFFFF;
  SHA1Consts := FastHashAlignedConst(P, SizeOf(P));
end;

{$POINTERMATH ON}
procedure SHA1CompressPascal(State: Pointer; Data: PByte; Blocks: NativeUInt);
var
  S: PCardinal;
  W: array[0..79] of Cardinal;
  A, B, C, D, E, T: Cardinal;
  I: Integer;
begin
  S := State;
  while Blocks > 0 do
  begin
    for I := 0 to 15 do
      W[I] := (Cardinal(Data[4 * I]) shl 24) or (Cardinal(Data[4 * I + 1]) shl 16) or
              (Cardinal(Data[4 * I + 2]) shl 8) or Cardinal(Data[4 * I + 3]);
    for I := 16 to 79 do
    begin
      T := W[I - 3] xor W[I - 8] xor W[I - 14] xor W[I - 16];
      W[I] := (T shl 1) or (T shr 31);
    end;
    A := S[0]; B := S[1]; C := S[2]; D := S[3]; E := S[4];
    for I := 0 to 79 do
    begin
      case I of
        0..19:  T := (D xor (B and (C xor D))) + $5A827999;
        20..39: T := (B xor C xor D) + $6ED9EBA1;
        40..59: T := ((B and C) or (D and (B or C))) + $8F1BBCDC;
      else
        T := (B xor C xor D) + $CA62C1D6;
      end;
      T := T + ((A shl 5) or (A shr 27)) + E + W[I];
      E := D; D := C; C := (B shl 30) or (B shr 2); B := A; A := T;
    end;
    Inc(S[0], A); Inc(S[1], B); Inc(S[2], C); Inc(S[3], D); Inc(S[4], E);
    Inc(Data, 64);
    Dec(Blocks);
  end;
end;
{$POINTERMATH OFF}

{$IF defined(CPUX64)}
  {$I Asm\SHA1.x64.inc}
{$ELSEIF defined(CPUX86)}
  {$I Asm\SHA1.x86.inc}
{$ENDIF}

function SHA1SetMaxLevel(MaxLevel: TFastHashLevel): TFastHashLevel;
{$IF defined(CPUX86) or defined(CPUX64)}
var
  Supported: TFastHashLevels;
{$ENDIF}
begin
{$IF defined(CPUX86) or defined(CPUX64)}
  Supported := FastHashSupportedLevels;
  if (MaxLevel >= fhlSHANI) and (fhlSHANI in Supported) then
  begin
    SHA1Compress := SHA1CompressSHANI;
    ActiveLevel := fhlSHANI;
  end
  else if (MaxLevel >= fhlAVX2) and (fhlAVX2 in Supported) then
  begin
    SHA1Compress := SHA1CompressAVX2;
    ActiveLevel := fhlAVX2;
  end
  else if (MaxLevel >= fhlScalar) and (fhlScalar in Supported) then
  begin
    SHA1Compress := SHA1CompressScalar;
    ActiveLevel := fhlScalar;
  end
  else
{$ENDIF}
  begin
    SHA1Compress := SHA1CompressPascal;
    ActiveLevel := fhlPascal;
  end;
  Result := ActiveLevel;
end;

function SHA1ActiveLevel: TFastHashLevel;
begin
  Result := ActiveLevel;
end;

initialization
  InitConsts;
  SHA1SetMaxLevel(High(TFastHashLevel));

end.
