unit FastHash.SHA512;

{
  SHA-384/SHA-512/SHA-512/224/SHA-512/256 block compression: Pascal
  reference plus two asm cores (Asm\SHA512.x86.inc / Asm\SHA512.x64.inc,
  generated by Tools\gen_sha512.pl):

    Scalar  SSE2 message schedule into a W+K table; rounds in 64-bit integer
            registers (Win64) or in the 64-bit lanes of xmm registers (Win32)
    AVX2    two blocks' schedule computed together in ymm registers; BMI2
            rounds (Win64) or VEX xmm rounds (Win32)

  There is no SHA-NI level: the SHA-512 instructions (VSHA512RNDS2) only
  exist on very recent CPUs and are not used here.
}

interface

{$I FastHash.inc}

uses
  FastHash.CPU;

type
  TSHA512CompressProc = TFastHashBlockProc;

var
  /// <summary>Compresses Blocks 128-byte blocks into State (8 UInt64).</summary>
  SHA512Compress: TSHA512CompressProc;

procedure SHA512CompressPascal(State: Pointer; Data: PByte; Blocks: NativeUInt);
function SHA512SetMaxLevel(MaxLevel: TFastHashLevel): TFastHashLevel;
function SHA512ActiveLevel: TFastHashLevel;
/// <summary>Name of the implementation in use, e.g. 'A64 asm'.</summary>
function SHA512ActiveImplementation: string;
/// <summary>Every implementation this CPU can run, Pascal first, in order of preference within each level.</summary>
function SHA512Implementations: TArray<TFastHashBlockImpl>;

implementation

{$Q-}{$R-}

const
  K512: array[0..79] of UInt64 = (
    $428a2f98d728ae22, $7137449123ef65cd, $b5c0fbcfec4d3b2f, $e9b5dba58189dbbc,
    $3956c25bf348b538, $59f111f1b605d019, $923f82a4af194f9b, $ab1c5ed5da6d8118,
    $d807aa98a3030242, $12835b0145706fbe, $243185be4ee4b28c, $550c7dc3d5ffb4e2,
    $72be5d74f27b896f, $80deb1fe3b1696b1, $9bdc06a725c71235, $c19bf174cf692694,
    $e49b69c19ef14ad2, $efbe4786384f25e3, $0fc19dc68b8cd5b5, $240ca1cc77ac9c65,
    $2de92c6f592b0275, $4a7484aa6ea6e483, $5cb0a9dcbd41fbd4, $76f988da831153b5,
    $983e5152ee66dfab, $a831c66d2db43210, $b00327c898fb213f, $bf597fc7beef0ee4,
    $c6e00bf33da88fc2, $d5a79147930aa725, $06ca6351e003826f, $142929670a0e6e70,
    $27b70a8546d22ffc, $2e1b21385c26c926, $4d2c6dfc5ac42aed, $53380d139d95b3df,
    $650a73548baf63de, $766a0abb3c77b2a8, $81c2c92e47edaee6, $92722c851482353b,
    $a2bfe8a14cf10364, $a81a664bbc423001, $c24b8b70d0f89791, $c76c51a30654be30,
    $d192e819d6ef5218, $d69906245565a910, $f40e35855771202a, $106aa07032bbd1b8,
    $19a4c116b8d2d0c8, $1e376c085141ab53, $2748774cdf8eeb99, $34b0bcb5e19b48a8,
    $391c0cb3c5c95a63, $4ed8aa4ae3418acb, $5b9cca4f7763e373, $682e6ff3d6b2b8a3,
    $748f82ee5defb2fc, $78a5636f43172f60, $84c87814a1f0ab72, $8cc702081a6439ec,
    $90befffa23631e28, $a4506cebde82bde9, $bef9a3f7b2c67915, $c67178f2e372532b,
    $ca273eceea26619c, $d186b8c721c0c207, $eada7dd6cde0eb1e, $f57d4f7fee6ed178,
    $06f067aa72176fba, $0a637dc5a2c898a6, $113f9804bef90dae, $1b710b35131c471b,
    $28db77f523047d84, $32caab7b40c72493, $3c9ebe0a15c9bebc, $431d67c49c100d4c,
    $4cc5d4becb3e42b6, $597f299cfc657e2a, $5fcb6fab3ad6faec, $6c44198c4a475817);

var
  Active: TFastHashBlockImpl;
  // K512 copied to a 64-byte aligned block for the SSE2 schedule (legacy-SSE
  // memory operands must be 16-byte aligned). The AVX2 code uses the named
  // rows in the .inc.
  SHA512Consts: PByte;

procedure InitConsts;
begin
  SHA512Consts := FastHashAlignedConst(K512, SizeOf(K512));
end;

{$POINTERMATH ON}
procedure SHA512CompressPascal(State: Pointer; Data: PByte; Blocks: NativeUInt);
var
  S: PUInt64;
  W: array[0..79] of UInt64;
  a, b, c, d, e, f, g, h, s0, s1, t1, t2: UInt64;
  I, J: Integer;

  function ROR(x: UInt64; n: Byte): UInt64; inline;
  begin
    Result := (x shr n) or (x shl (64 - n));
  end;

begin
  S := State;
  while Blocks > 0 do
  begin
    for I := 0 to 15 do
    begin
      W[I] := 0;
      for J := 0 to 7 do
        W[I] := (W[I] shl 8) or Data[8 * I + J];
    end;
    for I := 16 to 79 do
    begin
      s0 := ROR(W[I - 15], 1) xor ROR(W[I - 15], 8) xor (W[I - 15] shr 7);
      s1 := ROR(W[I - 2], 19) xor ROR(W[I - 2], 61) xor (W[I - 2] shr 6);
      W[I] := W[I - 16] + s0 + W[I - 7] + s1;
    end;
    a := S[0]; b := S[1]; c := S[2]; d := S[3];
    e := S[4]; f := S[5]; g := S[6]; h := S[7];
    for I := 0 to 79 do
    begin
      t1 := h + (ROR(e, 14) xor ROR(e, 18) xor ROR(e, 41)) + (g xor (e and (f xor g))) + K512[I] + W[I];
      t2 := (ROR(a, 28) xor ROR(a, 34) xor ROR(a, 39)) + ((a and b) or (c and (a or b)));
      h := g; g := f; f := e; e := d + t1;
      d := c; c := b; b := a; a := t1 + t2;
    end;
    Inc(S[0], a); Inc(S[1], b); Inc(S[2], c); Inc(S[3], d);
    Inc(S[4], e); Inc(S[5], f); Inc(S[6], g); Inc(S[7], h);
    Inc(Data, 128);
    Dec(Blocks);
  end;
end;
{$POINTERMATH OFF}

{$IFDEF FASTHASH_X86ASM}
  {$IF defined(CPUX64)}
    {$I Asm\SHA512.x64.inc}
  {$ELSE}
    {$I Asm\SHA512.x86.inc}
  {$ENDIF}
{$ENDIF}

{$IFDEF FASTHASH_ARM64}
procedure fh_sha512_asm(State: Pointer; Data: PByte; Blocks: NativeUInt); external FastHashArmObj name 'fh_sha512_asm';
procedure fh_sha512_c(State: Pointer; Data: PByte; Blocks: NativeUInt); external FastHashArmObj name 'fh_sha512_c';
procedure fh_sha512_ce_asm(State: Pointer; Data: PByte; Blocks: NativeUInt); external FastHashArmObj name 'fh_sha512_ce_asm';
procedure fh_sha512_ce_c(State: Pointer; Data: PByte; Blocks: NativeUInt); external FastHashArmObj name 'fh_sha512_ce_c';
{$ENDIF}

function SHA512Implementations: TArray<TFastHashBlockImpl>;
{$IFDEF FASTHASH_X86ASM}
var
  Supported: TFastHashLevels;
{$ENDIF}
begin
  // in order of preference within each level (see the README's benchmark notes)
  Result := [FastHashImpl('Pascal', fhlPascal, SHA512CompressPascal)];
{$IFDEF FASTHASH_X86ASM}
  Supported := FastHashSupportedLevels;
  if fhlScalar in Supported then
    Result := Result + [FastHashImpl('x86 asm', fhlScalar, SHA512CompressScalar)];
  if fhlSIMD in Supported then
    Result := Result + [FastHashImpl('AVX2 asm', fhlSIMD, SHA512CompressAVX2)];
{$ENDIF}
{$IFDEF FASTHASH_ARM64}
  Result := Result + [FastHashImpl('A64 asm', fhlScalar, fh_sha512_asm), FastHashImpl('C', fhlScalar, fh_sha512_c)];
  if CPUHasSHA512 then
    Result := Result + [FastHashImpl('CE asm', fhlCrypto, fh_sha512_ce_asm), FastHashImpl('CE C', fhlCrypto, fh_sha512_ce_c)];
{$ENDIF}
end;

function SHA512SetMaxLevel(MaxLevel: TFastHashLevel): TFastHashLevel;
begin
  Active := FastHashSelect(SHA512Implementations, MaxLevel);
  SHA512Compress := Active.Proc;
  Result := Active.Level;
end;

function SHA512ActiveLevel: TFastHashLevel;
begin
  Result := Active.Level;
end;

function SHA512ActiveImplementation: string;
begin
  Result := Active.Name;
end;

initialization
  InitConsts;
  SHA512SetMaxLevel(High(TFastHashLevel));

end.
