#!/usr/bin/perl
# Generates Asm\MD5.x86.inc and Asm\MD5.x64.inc: the fully unrolled scalar
# MD5 multi-block compress function for Win32 and Win64.
#
#   procedure MD5CompressScalar(State: Pointer; Data: PByte; Blocks: NativeUInt);
#
# State is 4 little-endian Cardinals (A, B, C, D). Run from the Hash folder:
#   perl Tools\gen_md5.pl
use strict;
use warnings;
use FindBin;

my $out_dir = "$FindBin::Bin/../Asm";

my @T = (
  0xd76aa478, 0xe8c7b756, 0x242070db, 0xc1bdceee, 0xf57c0faf, 0x4787c62a, 0xa8304613, 0xfd469501,
  0x698098d8, 0x8b44f7af, 0xffff5bb1, 0x895cd7be, 0x6b901122, 0xfd987193, 0xa679438e, 0x49b40821,
  0xf61e2562, 0xc040b340, 0x265e5a51, 0xe9b6c7aa, 0xd62f105d, 0x02441453, 0xd8a1e681, 0xe7d3fbc8,
  0x21e1cde6, 0xc33707d6, 0xf4d50d87, 0x455a14ed, 0xa9e3e905, 0xfcefa3f8, 0x676f02d9, 0x8d2a4c8a,
  0xfffa3942, 0x8771f681, 0x6d9d6122, 0xfde5380c, 0xa4beea44, 0x4bdecfa9, 0xf6bb4b60, 0xbebfbc70,
  0x289b7ec6, 0xeaa127fa, 0xd4ef3085, 0x04881d05, 0xd9d4d039, 0xe6db99e5, 0x1fa27cf8, 0xc4ac5665,
  0xf4292244, 0x432aff97, 0xab9423a7, 0xfc93a039, 0x655b59c3, 0x8f0ccc92, 0xffeff47d, 0x85845dd1,
  0x6fa87e4f, 0xfe2ce6e0, 0xa3014314, 0x4e0811a1, 0xf7537e82, 0xbd3af235, 0x2ad7d2bb, 0xeb86d391,
);
my @S = ([7, 12, 17, 22], [5, 9, 14, 20], [4, 11, 16, 23], [6, 10, 15, 21]);

sub hex32 { sprintf('$%08X', $_[0]) }

# Emits the 64 rounds. $r = { a,b,c,d,t1,t2,data }
sub rounds {
  my ($r) = @_;
  my @v = ($r->{a}, $r->{b}, $r->{c}, $r->{d});
  my ($t1, $t2, $p) = ($r->{t1}, $r->{t2}, $r->{data});
  my @o;
  for my $i (0 .. 63) {
    my $round = int($i / 16);
    my $j = $i % 16;
    my $k = $round == 0 ? $j
          : $round == 1 ? (1 + 5 * $j) % 16
          : $round == 2 ? (5 + 3 * $j) % 16
          :               (7 * $j) % 16;
    my $s = $S[$round][$j % 4];
    # step i works on (a,b,c,d) rotated right by i: a,d,c,b,a,...
    my ($a, $b, $c, $d) = @v[(0 - $i) % 4, (1 - $i) % 4, (2 - $i) % 4, (3 - $i) % 4];
    my $x = "dword ptr [$p + " . (4 * $k) . "]";
    my $tc = hex32($T[$i]);
    push @o, "    // step $i";
    if ($round == 0) {        # F = ((c xor d) and b) xor d
      push @o, "    mov   $t1, $c", "    add   $a, $x", "    xor   $t1, $d", "    add   $a, $tc",
               "    and   $t1, $b", "    xor   $t1, $d", "    add   $a, $t1";
    } elsif ($round == 1) {   # G = (b and d) + (c and not d)   (disjoint bits)
      push @o, "    mov   $t1, $d", "    add   $a, $x", "    not   $t1", "    add   $a, $tc",
               "    and   $t1, $c", "    mov   $t2, $d", "    add   $a, $t1", "    and   $t2, $b",
               "    add   $a, $t2";
    } elsif ($round == 2) {   # H = b xor c xor d
      push @o, "    mov   $t1, $c", "    add   $a, $x", "    xor   $t1, $d", "    add   $a, $tc",
               "    xor   $t1, $b", "    add   $a, $t1";
    } else {                  # I = c xor (b or not d)
      push @o, "    mov   $t1, $d", "    add   $a, $x", "    not   $t1", "    add   $a, $tc",
               "    or    $t1, $b", "    xor   $t1, $c", "    add   $a, $t1";
    }
    push @o, "    rol   $a, $s", "    add   $a, $b";
  }
  return @o;
}

sub header {
  return (
    "// GENERATED by Tools\\gen_md5.pl - do not edit by hand.",
    "",
    "procedure MD5CompressScalar(State: Pointer; Data: PByte; Blocks: NativeUInt);",
  );
}

# ---------------- Win64 ----------------
{
  my @o = header();
  push @o, "asm",
    "    // rcx = State, rdx = Data, r8 = Blocks",
    "    .PUSHNV rsi",
    "    .PUSHNV rdi",
    "    .PUSHNV r12",
    "    test  r8, r8",
    "    jz    \@done",
    "    mov   rdi, rcx",
    "    mov   rsi, rdx",
    "    mov   r12, r8",
    "    shl   r12, 6",
    "    add   r12, rsi                // r12 = end of data",
    "    mov   r8d, [rdi]",
    "    mov   r9d, [rdi + 4]",
    "    mov   r10d, [rdi + 8]",
    "    mov   r11d, [rdi + 12]",
    "\@block:";
  push @o, rounds({ a => 'r8d', b => 'r9d', c => 'r10d', d => 'r11d', t1 => 'eax', t2 => 'ecx', data => 'rsi' });
  push @o,
    "    add   r8d, [rdi]",
    "    add   r9d, [rdi + 4]",
    "    add   r10d, [rdi + 8]",
    "    add   r11d, [rdi + 12]",
    "    mov   [rdi], r8d",
    "    mov   [rdi + 4], r9d",
    "    mov   [rdi + 8], r10d",
    "    mov   [rdi + 12], r11d",
    "    add   rsi, 64",
    "    cmp   rsi, r12",
    "    jb    \@block",
    "\@done:",
    "end;", "";
  write_file("$out_dir/MD5.x64.inc", @o);
}

# ---------------- Win32 ----------------
{
  my @o = header();
  push @o, "asm",
    "    // eax = State, edx = Data, ecx = Blocks",
    "    test  ecx, ecx",
    "    jz    \@exit",
    "    push  ebx",
    "    push  esi",
    "    push  edi",
    "    push  ebp",
    "    mov   esi, edx",
    "    shl   ecx, 6",
    "    add   ecx, edx",
    "    push  ecx                     // [esp + 4] = end of data",
    "    push  eax                     // [esp]     = State",
    "    mov   edi, eax",
    "    mov   eax, [edi]",
    "    mov   ebx, [edi + 4]",
    "    mov   ecx, [edi + 8]",
    "    mov   edx, [edi + 12]",
    "\@block:";
  push @o, rounds({ a => 'eax', b => 'ebx', c => 'ecx', d => 'edx', t1 => 'edi', t2 => 'ebp', data => 'esi' });
  push @o,
    "    mov   edi, [esp]",
    "    add   eax, [edi]",
    "    add   ebx, [edi + 4]",
    "    add   ecx, [edi + 8]",
    "    add   edx, [edi + 12]",
    "    mov   [edi], eax",
    "    mov   [edi + 4], ebx",
    "    mov   [edi + 8], ecx",
    "    mov   [edi + 12], edx",
    "    add   esi, 64",
    "    cmp   esi, [esp + 4]",
    "    jb    \@block",
    "    add   esp, 8",
    "    pop   ebp",
    "    pop   edi",
    "    pop   esi",
    "    pop   ebx",
    "\@exit:",
    "end;", "";
  write_file("$out_dir/MD5.x86.inc", @o);
}

sub write_file {
  my ($name, @lines) = @_;
  open(my $fh, '>:crlf', $name) or die "$name: $!";
  print $fh join("\n", @lines);
  close $fh;
  print "wrote $name\n";
}
